#https://pre-commit.com/hooks.html
---
repos:
- repo: local
  hooks:
  - id: immutable-setup-py
    name: Verify that setup.py stays immutable
    description: >-
      This is a sanity check that makes sure that
      the `setup.py` file isn't changed.
    # Using Python here because using
    # shell test does not seem to work in CIs:
    entry: >-
      sh -c 'git hash-object setup.py
      |
      python -c raise\ SystemExit\(input\(\)\ !=\ \"b72e95ce049c4c67c6487a2171fec8d1b0b958b1\"\)
      '
    pass_filenames: false
    language: system
    files: >-
      ^setup\.py$
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v3.2.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
    exclude: >
      (?x)^(
        test/(with-skip-tag-id|unicode).yml|
        examples/example.yml
      )$
  - id: mixed-line-ending
  - id: check-byte-order-marker
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: debug-statements
  - id: end-of-file-fixer
  - id: check-docstring-first
  - id: check-json
  - id: check-added-large-files
  - id: check-yaml
  - id: debug-statements
  - id: name-tests-test
  - id: double-quote-string-fixer
  - id: requirements-txt-fixer
    #  - id: detect-aws-credentials # no aws at this moment
  - id: detect-private-key
  - id: no-commit-to-branch
    args: ['--branch', 'master']
    language_version: python3
#- repo: https://github.com/adrienverge/yamllint.git
#  rev: v1.24.2
#  hooks:
#  - id: yamllint
#    files: \.(yaml|yml)$
#    types: [file, yaml]
#    entry: yamllint --strict

- repo: https://gitlab.com/pycqa/flake8.git
  rev: 3.8.3
  hooks:
  - id: flake8
    language_version: python3
    additional_dependencies:
    - flake8-2020>=1.6.0
    - flake8-docstrings>=1.5.0
    - flake8-pytest-style>=1.2.2
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.782
  hooks:
  - id: mypy
    # empty args needed in order to match mypy cli behavior
    args: []
    additional_dependencies:
    - Sphinx>=3.1.2
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: v2.6.0
  hooks:
  - id: pylint

- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    language_version: python3


- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.1
  hooks:
  - id: htmlhint
    # optional custom config:
    args: [--config, .htmlhintrc]
  - id: htmllint
    args: [--indent, "    ", -i]
  - id: dockerfile_lint
    # optional custom config:
    args: [--json, --verbose, --dockerfile]

- repo: https://github.com/pre-commit/mirrors-ruby-lint
  rev: 'v2.3.1-1'  # Use the sha / tag you want to point at
  hooks:
  -   id: ruby-lint

- repo: https://github.com/pre-commit/mirrors-scss-lint
  rev: 'v0.59.0'  # Use the sha / tag you want to point at
  hooks:
  -   id: scss-lint

- repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
  rev: v0.1.0
  hooks:
  - id: dockerfilelint
    stages: [commit]

#- repo: https://github.com/shellcheck-py/shellcheck-py
#  rev: v0.7.1.1
#  hooks:
#  - id: shellcheck

- repo: git@github.com:Yelp/detect-secrets
  rev: v0.14.3
  hooks:
  - id: detect-secrets
    args: ['--baseline', '.secrets.baseline']
    exclude: .*/tests/.*

#- repo: https://github.com/ansible/ansible-lint.git
#  rev: v4.3.5
#  hooks:
#  -   id: ansible-lint
#      files: \.(yaml|yml)$
